import { test, expect } from '@playwright/test';

// The knowledge map is a levelled set of data flow diagrams: a context diagram,
// one level-1 diagram of the apps, and a level-2 and level-3 diagram per app
// that has been decomposed. Every diagram below level 0 is generated by
// scripts/build-dfd.cjs, so these tests assert the navigation rather than the
// wording of any one bubble.
test.describe('Knowledge Map and Viewer', () => {
  test('drills from the context diagram to level 1 and into an app', async ({ page }) => {
    await page.goto('/knowledge/KNOWLEDGE_MAP.html');
    await expect(page.locator('h1')).toContainText('Context Diagram');

    await page.locator('a[href="DFD_LEVEL1.html"]').first().click();
    await expect(page.locator('h1')).toContainText('Level 1', { timeout: 10000 });

    await page.locator('a[href="DFD_LEVEL2_YIELDCURVES.html"]').first().click();
    await expect(page.locator('h1')).toContainText('Yield Curves', { timeout: 10000 });
  });

  test('reaches a process spec from a level-2 bubble', async ({ page }) => {
    await page.goto('/knowledge/DFD_LEVEL2_YIELDCURVES.html');

    // 3.3 Adjust for other effects. Its bubble opens the spec named for it.
    await page.locator('a.process[href*="3.3_SAO_Adjustment.md"]').first().click();
    await expect(page).toHaveURL(/3\.3_SAO_Adjustment\.md/, { timeout: 10000 });
    await expect(page.locator('h1')).toContainText('SAO');
  });

  test('reaches the parent spec from a diagram header', async ({ page }) => {
    await page.goto('/knowledge/DFD_LEVEL3_YC_LOAD.html');
    await expect(page.locator('h1')).toContainText('3.1');

    await page.locator('a.spec-link').click();
    await expect(page).toHaveURL(/3\.1_Load_And_Parse\.md/, { timeout: 10000 });
  });

  test('a leaf process spec names the code that implements it', async ({ page }) => {
    await page.goto('/knowledge/viewer.html#/md/YieldCurves/knowledge/3.1_Load_And_Parse.md');
    const body = page.locator('#content');
    await expect(body).toContainText('parseRefCpiAndSaFactors', { timeout: 15000 });
    await expect(body).toContainText('Specifies:');
    await expect(body).toContainText('Implemented by:');
  });

  test('toggles a CSV preview in the DataStores doc', async ({ page }) => {
    await page.goto('/knowledge/viewer.html#/md/knowledge/DataStores.md');

    const viewLink = page.locator('a:has-text("View")').first();
    await expect(viewLink).toBeVisible({ timeout: 10000 });
    await viewLink.click();

    // The container appears at once and then holds either the parsed table or
    // an error, depending on whether the browser can reach the store.
    const container = page.locator('.csv-preview-container');
    await expect(container).toBeVisible({ timeout: 10000 });
    await expect(container.locator('.csv-preview, p')).toBeVisible({ timeout: 15000 });

    if (await page.locator('.csv-preview').isVisible()) {
      await viewLink.click();
      await expect(page.locator('.csv-preview')).not.toBeVisible();
    }
  });

  test('follows an internal link inside a rendered mermaid diagram', async ({ page }) => {
    await page.goto('/knowledge/viewer.html#/md/knowledge/TipsLadderManager.md');

    const mermaidSvg = page.locator('.mermaid svg');
    await expect(mermaidSvg).toBeVisible({ timeout: 15000 });

    const link = page.locator('.mermaid a').first();
    await link.click();

    // The target is whatever the diagram currently points at; what matters is
    // that the click loads another document rather than leaving the viewer.
    await expect(page).toHaveURL(/#\/md\/.+\.md/, { timeout: 10000 });
    await expect(page).not.toHaveURL(/TipsLadderManager\.md$/);
    await expect(page.locator('#content h1')).toBeVisible({ timeout: 10000 });
  });

  test('renders LaTeX math via KaTeX, not raw source', async ({ page }) => {
    await page.goto('/knowledge/viewer.html#/md/YieldCurves/knowledge/3.2_Seasonal_Adjustments.md');

    const katex = page.locator('.katex').first();
    await expect(katex).toBeVisible({ timeout: 15000 });

    const body = await page.locator('#content').innerText();
    expect(body).not.toContain('\\frac');
    expect(body).not.toContain('P_{SA}');
  });

  test('shows an error for a file that does not exist', async ({ page }) => {
    await page.goto('/knowledge/viewer.html#/md/knowledge/NonExistent.md');
    await expect(page.locator('.error')).toBeVisible();
    await expect(page.locator('.error')).toContainText('Failed to load');
  });
});
